In [2]:
import numpy as np

## 1. Datatypes & Attributes

In [3]:
# Numpy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

In [6]:
a3 = np.array([
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]],
    [[10, 11, 12],
     [13, 14, 15],
     [16, 17, 18]]
])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [11]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [12]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [13]:
type(a1)

numpy.ndarray

In [14]:
# Create a DataFrame from a NumPy array
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating Arrays

In [15]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [16]:
sample_array.dtype

dtype('int64')

In [21]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
ones.dtype

dtype('float64')

In [23]:
type(ones)

numpy.ndarray

In [25]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [32]:
random_array = np.random.randint(1, 10, size=(3, 5))
random_array

array([[2, 5, 5, 8, 2],
       [6, 6, 2, 4, 8],
       [4, 7, 7, 1, 3]])

In [34]:
np.random.random((5,3))

array([[0.97276801, 0.17648365, 0.75644436],
       [0.89951678, 0.93917609, 0.26847899],
       [0.06745449, 0.39360355, 0.83889892],
       [0.09320972, 0.34514281, 0.16737556],
       [0.35759615, 0.27575313, 0.11449462]])

In [39]:
np.random.rand(5, 3)

array([[0.82657057, 0.36346035, 0.51826656],
       [0.81938007, 0.75188282, 0.47265043],
       [0.1911503 , 0.264298  , 0.91735197],
       [0.29249317, 0.87242461, 0.68887764],
       [0.15633265, 0.09425902, 0.08427095]])

In [44]:
# Pseudo-random numbers
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

## 3. Viewing arrays and matrices

In [45]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
random_array_4[0]

array([5, 0, 3])

In [47]:
random_array_4.shape

(5, 3)

In [52]:
random_array_4[:3, :2]

array([[5, 0],
       [3, 7],
       [3, 5]])

In [70]:
a4 = np.random.randint(10, size=(3,4,5))
a4

array([[[0, 4, 8, 4, 3],
        [3, 8, 8, 7, 0],
        [3, 8, 7, 7, 1],
        [8, 4, 7, 0, 4]],

       [[9, 0, 6, 4, 2],
        [4, 6, 3, 3, 7],
        [8, 5, 0, 8, 5],
        [4, 7, 4, 1, 3]],

       [[3, 9, 2, 5, 2],
        [3, 5, 7, 2, 7],
        [1, 6, 5, 0, 0],
        [3, 1, 9, 9, 6]]])

In [71]:
a4[1, :4, 1]

array([0, 6, 5, 7])

In [72]:
a4.ndim, a4.shape

(3, (3, 4, 5))

## 4. Manipulating & comparing arrays

### Arithmetic

In [73]:
a1

array([1, 2, 3])

In [80]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [81]:
a1 + ones

array([2., 3., 4.])

In [82]:
a1 * ones

array([1., 2., 3.])

In [87]:
a1

array([1, 2, 3])

In [83]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [84]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [89]:
# How can you reshape a2 to be compatible with a3?
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [95]:
a2.shape

(2, 3)

In [96]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

array([[[1. , 2. , 3.3]],

       [[4. , 5. , 6.5]]])

### Aggregation